[package]
name = "mordle2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
itertools = "0.14"
log = { version = "0.4", features = ["std"] }
logging_timer = "1"
rand = "0.9"
roaring = "0.11"
thiserror = "2"
unicode-segmentation = "1"
unicode-normalization = "0.1"
